### ISSUE TITLE
file_put_contents() warnings on older IND-files

### ISSUE THREAD

**Issue by yvettejolie** [Gymnasiast/Davitools#1]
First off, thank you so much for making this tool! Ran into it on the Tweakers post about Milan Polle.
I have also grown up with the Davilex games like RedCat and A2 Racer, so it's fun to poke around in the old game files and feel the nostalgia.

I used your tool on A2 Racer 4, worked like a charm!
Then I tried using it on A2 Racer II and A2 Racer III (the Dutch games). The tool can read the IND file, it even lists all the files inside, but instead of extracting anything, it just gives me a warning for each file: "Warning:  file_put_contents() expects parameter 1 to be a valid path, string given in rcs-extract.php on line 45". I suspect it's a problem with the IND-files, but I haven't figured out what.

I was wondering if you would be able to look into it?

All the best to you!

**Comment by Gymnasiast** [comment]
Hey, wat leuk om te horen dat mijn project tenminste één andere gebruiker heeft!

Ik heb pas A2 Racer II in huis gehaald (ben recentelijk begonnen met het aanleggen van een collectie van de Davilex-racespellen), dus ik zal eens kijken.

**Comment by Gymnasiast** [comment]
Ik heb zojuist een fix gepusht, kun je die even proberen?

**Comment by yvettejolie** [comment]
Wow, had niet verwacht zo snel een reactie te krijgen, laat staan een fix!
Heb het geprobeerd en kan bevestigen dat het werkt voor zowel A2 Racer II en A2 Racer III Europa Tour.

Ontzettend bedankt! :)

**Comment by Gymnasiast** [comment]
Graag gedaan, voor mij is het ook nostalgie!

Sterker nog, je hebt me geïnspireerd om het script uit te breiden met de mogelijkheid om rcs.ind/.img ook te genereren. Heb dat zojuist getest door extra muziek toe te voegen aan Vakantie Racer :D

Als je dat ook wilt doen, dan kan ik wel wat instructies toevoegen.

**Comment by yvettejolie** [comment]
Super cool! Ik heb je comment ook gezien dat je graag een remake zou maken/zien.

Dat zou mij ook heel tof lijken. Dan wel met betere besturing en graphics, maar wel met al die typische dingetjes; de gekke namen voor de auto’s, al het straatmeubilair omver kunnen rijden, die houterige stemmen van de agenten, de mogelijkheid om te kiezen voor de “Original soundtrack”…

Én verbeterde scenery, wat meer “natuurgetrouw”; nu met Google maps ter referentie zou dat wel makkelijker moeten gaan dan eind jaren ’90! Meer gedetailleerde omgevingen, meer mogelijkheden om eens een stukje af te snijden of een af-/opritje mee te pakken, meer steden en snelweg, misschien ook volk in de straten die aan de kant springen à la Midtown Madness zodat het geen bloedbad wordt à la GTA?

Het zal er wel nooit van komen, maar dromen kan altijd toch?
Ik wou dat ik wist hoe ik spelletjes kon maken, dan wist ik wel wat ik (in m’n vrije tijd) zou doen! :D
